os:
- osx
- linux
osx_image: xcode7.3
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
matrix:
  fast_finish: true
  include:
    - os: osx
      node_js: "5"
    - os: linux
      node_js: "5"
      env: BROWSER_TESTS=1 SAUCE_USERNAME=testem-ci SAUCE_ACCESS_KEY=1f00979e-0252-4d69-98ff-f6c85d1a746b
  exclude:
    - os: osx
sudo: false
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update;
      brew install phantomjs;
    fi
  - npm config set spin false
install:
  - travis_retry npm install
before_script:
  - npm run lint
script:
  - npm run test
  - npm run integration
deploy:
  provider: npm
  email: "vanuan@gmail.com"
  api_key: "OmOY+DcRDPy1uoH2d8al2B+7xpfyY8dFKvNBBV/L2vRbzAj2GtPuaYzoWAhipcDyvlnp1BFGERwxYnbl6WMONg0kJKBsaaNcK3OgaTh61UUyeFqRR7rGJ3VNPNmdxDP/QuRoqh/I5iUjEM3JH4eTUxZwECQghDTTcbdIbisGZI4VYpoKSF3HOsoeZ+LwO18Z0bGblAoLPxOD/iVvXtWyQQtYCspY3/8RBTxSqsjqK3pvvNjJ61exVqjgBYnzmEmtEZ144qxs+N+NALC+k7ylKvCSTvH5XSyNTfaSQ9lPIka7vZ5CJbUB/ZjG8PDyWnaKPmjNpe06SnvXMjKMVYgEtsMQGQlNjztPNVE2fLilGyaZHgCQ7mGZIqYiDQWH4cZttXAZua7o+AJqf4Xnxuos0D0I5XqDDYHJTreZccQhd5NQL8IRMgKuKx4QscDgqc2FDo6L0sIruDFyt/IKXDbEiIj8nx4vMf+1oYNxQLwpjjuKX1JgWPGUT0D+yxdNk+RjPjU9/VyucShsKdzij4IG3TlT+TqrL46JFNtr22G3/n/e89OPDRWH/0rIJ5OChAV2/Jfkbz8jV5KM0sxCOgLRTCz8MnbMKfNKQfxYauhwkn4+Fov54msHcN72cqsHxTa6pkttdWytsKiiW0PLMEYaWJpKIFjQ6500BFLmjn0pA3M="
