# http://www.appveyor.com/docs/appveyor-yml

environment:
  INTEGRATION_TESTS_CONCURRENCY: 5
  matrix:
  - PHANTOM_SRC: "npm"
  # - PHANTOM_SRC: "chocolatey"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of nodejs
  - ps: Install-Product node 4
  - npm version
  - npm config set spin false
  - IF %PHANTOM_SRC%==npm appveyor-retry npm install -g phantomjs-prebuilt
  - IF %PHANTOM_SRC%==chocolatey appveyor-retry cinst PhantomJS -y
  - phantomjs -v
  - appveyor-retry npm install

# Post-install test scripts.
test_script:
  - cmd: npm run testem-tests
  - cmd: npm run integration

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
